version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
        - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:11.5
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: polisportiva
