version: '3'

services:

  db:
    image: postgres:11.5
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: polisportiva
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  app:
    build:
      context: .
      dockerfile: ${DOCKER_FILE:-Dockerfile}
    expose:
        - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=polisportiva
      - DB_USER=admin
      - DB_PASSWORD=admin