micronaut:
  application:
    name: polisportiva-micronaut

## Hibernate Properties
jpa:
  default:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update

# Database Properties
datasources:
  default:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driverClassName: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    username: ${DB_USER}
    password: ${DB_PASSWORD}

#datasources:
#  default:
#    url: jdbc:postgresql://db:5432/polisportiva
#    driverClassName: org.postgresql.Driver
#    db-type: postgres
#    dialect: POSTGRES
#    username: admin
#    password: admin

#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/polisportiva
#    driver-class-name: org.postgresql.Driver
#    db-type: postgres
#    dialect: POSTGRES
#    username: postgres
#    password: postgres

netty:
  default:
    allocator:
      max-order: 3
